-- MySQL Script generated by MySQL Workbench
-- Sun Jul 26 03:02:11 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AlkeWallet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AlkeWallet` ;

-- -----------------------------------------------------
-- Schema AlkeWallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlkeWallet` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `AlkeWallet` ;

-- -----------------------------------------------------
-- Table `AlkeWallet`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`User` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `uq_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlkeWallet`.`Currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Currency` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Currency` (
  `currency_id` INT NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(50) NOT NULL,
  `currency_symbol` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`currency_id`),
  UNIQUE INDEX `uq_currency_name` (`currency_name` ASC) VISIBLE,
  UNIQUE INDEX `uq_currency_symbol` (`currency_symbol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlkeWallet`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Account` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  `current_balance` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `is_default` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `uq_account_user_currency` (`user_id` ASC, `currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `AlkeWallet`.`User` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_account_currency_id`
    FOREIGN KEY (`currency_id`)
    REFERENCES `AlkeWallet`.`Currency` (`currency_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlkeWallet`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `importe` DECIMAL(15,2) NOT NULL,
  `transaction_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sender_account_id` INT NOT NULL,
  `receive_account_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `idx_receive_account_id` (`receive_account_id` ASC) VISIBLE,
  INDEX `idx_sender_account_id` (`sender_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_sender_account_id`
    FOREIGN KEY (`sender_account_id`)
    REFERENCES `AlkeWallet`.`Account` (`account_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_transaction_receive_account_id`
    FOREIGN KEY (`receive_account_id`)
    REFERENCES `AlkeWallet`.`Account` (`account_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Validaciones de integridad para Account
-- -----------------------------------------------------
ALTER TABLE `AlkeWallet`.`Account`
ADD CONSTRAINT `chk_account_balance_non_negative`
CHECK (`current_balance` >= 0);

-- -----------------------------------------------------
-- Validación de importe positivo en Transaction
-- -----------------------------------------------------
ALTER TABLE `AlkeWallet`.`Transaction`
ADD CONSTRAINT `chk_transaction_amount_positive`
CHECK (`importe` > 0);

-- -----------------------------------------------------
-- Validación de cuentas distintas en Transaction
-- -----------------------------------------------------
ALTER TABLE `AlkeWallet`.`Transaction`
ADD CONSTRAINT `chk_transaction_accounts_different`
CHECK (`sender_account_id` <> `receive_account_id`);
    
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
