-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 18:57:04 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AlkeWallet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AlkeWallet` ;

-- -----------------------------------------------------
-- Schema AlkeWallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlkeWallet` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `AlkeWallet` ;

-- -----------------------------------------------------
-- Table `AlkeWallet`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Users` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `current_balance` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlkeWallet`.`Currencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Currencies` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Currencies` (
  `currency_id` INT NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(50) NOT NULL,
  `currency_symbol` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`currency_id`),
  UNIQUE INDEX `currency_name_UNIQUE` (`currency_name` ASC) VISIBLE,
  UNIQUE INDEX `currency_symbol_UNIQUE` (`currency_symbol` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlkeWallet`.`Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Transactions` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `importe` DECIMAL(15,2) NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `receiver_user_id` INT NOT NULL,
  `sender_user_id` INT NOT NULL,
  `currency_id` INT NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `idx_receiver_user_id` (`receiver_user_id` ASC) VISIBLE,
  INDEX `idx_sender_user_id` (`sender_user_id` ASC) VISIBLE,
  INDEX `idx_currency_id` (`currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_receiver_user_id`
    FOREIGN KEY (`receiver_user_id`)
    REFERENCES `AlkeWallet`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_sender_user_id`
    FOREIGN KEY (`sender_user_id`)
    REFERENCES `AlkeWallet`.`Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transaction_currency_id`
    FOREIGN KEY (`currency_id`)
    REFERENCES `AlkeWallet`.`Currencies` (`currency_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
