-- MySQL Script generated by MySQL Workbench
-- Sun Sep 13 21:38:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alkewallet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `alkewallet` ;

-- -----------------------------------------------------
-- Schema alkewallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alkewallet` ;
USE `alkewallet` ;

-- -----------------------------------------------------
-- Table `currencies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `currencies` ;

CREATE TABLE IF NOT EXISTS `currencies` (
  `currency_id` INT NOT NULL AUTO_INCREMENT,
  `currency_name` VARCHAR(50) COLLATE 'utf8mb3_bin' NOT NULL,
  `currency_symbol` VARCHAR(5) COLLATE 'utf8mb3_bin' NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`currency_id`),
  UNIQUE INDEX `uq_currency_name` (`currency_name` ASC) VISIBLE,
  UNIQUE INDEX `uq_currency_symbol` (`currency_symbol` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(150) COLLATE 'utf8mb3_bin' NOT NULL,
  `first_name` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `last_name` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL DEFAULT '',
  `email` VARCHAR(150) COLLATE 'utf8mb3_bin' NOT NULL,
  `password` VARCHAR(255) COLLATE 'utf8mb3_bin' NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Indica si el usuario esta activo (1) o no (0)',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Fecha y hora de la ultima actualizacion del registro',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `uq_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 22;


-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `accounts` ;

CREATE TABLE IF NOT EXISTS `accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `cbu` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL COMMENT 'Numero de cuenta o CBU transaccional',
  `currency_id` INT NOT NULL,
  `current_balance` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `is_default` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `uq_account_user_currency` (`user_id` ASC, `currency_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_accounts_cbu` (`cbu` ASC) VISIBLE,
  INDEX `fk_account_currency_id` (`currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_currency_id`
    FOREIGN KEY (`currency_id`)
    REFERENCES `currencies` (`currency_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_account_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 29;


-- -----------------------------------------------------
-- Table `payees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `payees` ;

CREATE TABLE IF NOT EXISTS `payees` (
  `payee_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL COMMENT 'ID del usuario dueno de la agenda',
  `full_name` VARCHAR(255) CHARACTER SET 'utf8mb3' NOT NULL COMMENT 'Nombre y apellido en una sola fila',
  `cbu` VARCHAR(50) CHARACTER SET 'utf8mb3' NOT NULL COMMENT 'Numero de cuenta o CBU',
  `alias` VARCHAR(100) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL COMMENT 'Alias bancario',
  `currency_id` INT NOT NULL COMMENT 'Divisa de la cuenta del beneficiario',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`payee_id`),
  INDEX `fk_payees_user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_payees_currency_id` (`currency_id` ASC) VISIBLE,
  INDEX `idx_payees_cbu` (`cbu` ASC) VISIBLE,
  CONSTRAINT `fk_payees_currency_id`
    FOREIGN KEY (`currency_id`)
    REFERENCES `currencies` (`currency_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_payees_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5;


-- -----------------------------------------------------
-- Table `transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transactions` ;

CREATE TABLE IF NOT EXISTS `transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `importe` DECIMAL(15,2) NOT NULL,
  `transaction_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sender_account_id` INT NOT NULL,
  `receive_account_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`transaction_id`),
  INDEX `idx_receive_account_id` (`receive_account_id` ASC) VISIBLE,
  INDEX `idx_sender_account_id` (`sender_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_receive_account_id`
    FOREIGN KEY (`receive_account_id`)
    REFERENCES `accounts` (`account_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_transaction_sender_account_id`
    FOREIGN KEY (`sender_account_id`)
    REFERENCES `accounts` (`account_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 111;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
