-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 14:54:31 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AlkeWallet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AlkeWallet` ;

-- -----------------------------------------------------
-- Schema AlkeWallet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlkeWallet` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `AlkeWallet` ;

-- -----------------------------------------------------
-- Table `AlkeWallet`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Usuarios` (
  `user_id` INT NOT NULL,
  `nombre` VARCHAR(150) NULL,
  `correo_electronico` VARCHAR(150) NULL,
  `contraseña` VARCHAR(255) NULL,
  `saldo` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlkeWallet`.`Monedas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Monedas` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Monedas` (
  `currency_id` INT NOT NULL,
  `currency_name` VARCHAR(50) NULL,
  `currency_symbol` VARCHAR(50) NULL,
  PRIMARY KEY (`currency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlkeWallet`.`Transacciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AlkeWallet`.`Transacciones` ;

CREATE TABLE IF NOT EXISTS `AlkeWallet`.`Transacciones` (
  `transaction_id` INT NOT NULL,
  `importe` INT NULL,
  `transaction_date` DATE NULL,
  `receiver_user_id` INT NULL,
  `sender_user_id` INT NULL,
  PRIMARY KEY (`transaction_id`),
  CONSTRAINT `fk_transaction_receiver_user_id`
    FOREIGN KEY (`receiver_user_id`)
    REFERENCES `AlkeWallet`.`Usuarios` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_sender_user_id`
    FOREIGN KEY (`sender_user_id`)
    REFERENCES `AlkeWallet`.`Usuarios` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
